### ISSUE TITLE
Preparation for voting - checklist

### ISSUE THREAD

**Issue by rantav** [rantav/reversim-summit-2017#19]
The voting phase begins July 21. 
Here's what we need working: 

# Checklist 
- [x] Freeze edits. Do not allow submitters to edit. Allow moderators to edit (in case there's a special request - it's fine as long as we control it)
- [x] Display sessions in random order. The order must be consistent for a user (e.g. remain the same order when I refresh), but random between users so that voting would be fair. 
- [x] Enable voting. A logged in user needs to be able to vote. The user should also be able to undo her vote. The user should be able to see her voted sessions. But except for this user, nobody else (except site admins) should have access to the vote count or the names of the voters
